language: go

go:
  - 1.11.x

go_import_path: gopkg.in/src-d/go-billy-gluster.v0

dist: xenial
addons:
  apt:
    update: true
    packages:
      - glusterfs-common

services:
  - docker

before_script:
  - make container

script:
  - cp Gopkg.testing Gopkg.toml
  - make godep
  - make dependencies
  - go test -v ./... -check.vv
  - make test-coverage
  - make codecov
